# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Worksheet'),
        ),
    ]
